name: Tests

on:
  pull_request:
    branches:
      - '**'

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 18
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies and prepare wallet
        run: | 
          npm run blockchain:prepare

      - name: Run Forge build
        working-directory: ./boardwalk-contracts
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        working-directory: ./boardwalk-contracts
        run: |
          forge test -vvv
        id: test

      - name: Start blockchain
        run: |
          anvil &
          sleep 5

      - name: Install npm deps
        run: npm ci

      - name: Run tests
        run: |
          npm run test

      - name: Stop blockchain
        run: |
          killall anvil
